version: '3.8'

services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/mnt/config
    command: -config.file=/mnt/config/loki-config.yaml

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./Grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - ./Grafana/config/provisioning:/etc/grafana/provisioning
      - ./Grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - zipkin
      - loki
      - prometheus