global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'DMS-API'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:7212']