apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    uid: PBFA97CFB590B2093

  - name: Zipkin
    type: zipkin
    access: proxy
    url: http://host.docker.internal:9411
    jsonData:
      httpHeaderName1: "Content-Type"
      httpHeaderValue1: "application/json"
    uid: ZipkinDataSource

  - name: Loki
    type: loki
    access: proxy
    url: http://host.docker.internal:3100
    uid: LokiDataSource